### ISSUE TITLE
`SecurityConfig` 에서 `jwtAuthenticationFilter`를 이중으로 추가하는 문제가 있습니다.

### ISSUE THREAD

**Issue by bezzang-dev** [koritsu/spring-security-in-msa-example#1]
안녕하세요! msa 예제를 참고하여 많은 도움을 받고 있습니다. 
예제 코드를 보면서 이중으로 Filter를 등록하고 있는 코드를 발견해서 이렇게 이슈를 작성하게 되었습니다.

## 문제 상황

[Spring Docs](https://docs.spring.io/spring-boot/reference/web/reactive.html#web.reactive.webflux.web-filters) 문서를 참고해보시면, 

> WebFilter beans found in the application context will be automatically used to filter each exchange.

Bean에 등록된 WebFilter는 자동으로 filter에 등록된다고 기술되어 있습니다.
하지만 아래 코드에서 `jwtAuthenticationFilter`을 Bean에도 등록하고 Security Filter Chain에도 등록하고 있어서
결과적으로 같은 Filter를 2번 실행하고 있습니다.

https://github.com/koritsu/spring-security-in-msa-example/blob/62c5ec66be45493ab904f817d2eaf9552b475442/gateway-service/src/main/java/com/example/gatewayservice/config/SecurityConfig.java#L38-L48

## 해결 방안

1.  `jwtAuthenticationFilter`를 Bean에 등록하지 않고, SecurityFilterChain에만 등록합니다.
2. 또는 SecurityFilterChain에서 `jwtAuthenticationFilter`지우고, 순서를 보장하기 위해서  `@Order`를 지정합니다.

**Comment by koritsu** [comment]
@kimjinmyeong  

안녕하세요 말씀주신 이슈 확인했습니다.

좀 더 자세히 찾아보니 

SpringCloudGateway에 Spring Security 설정을 하게

요청을 받게 되면 하기 두 개의 exchange가 생기게 됩니다.

DefaultServerWebExchange - WebFlux의 일반적인 요청 처리
SecurityContextServerWebExchange - DefaultServerWebExchange를 감싸고 보안 관련 처리를 추가 (Spring Security의 인증/인가 관련 처리)

WebFilter interface로 만들어서 @Bean 으로 등록하면 DefaultWebFilterChain이 만들어질 때 List<WebFilter>를 가지게 되는데, Spring이 이 때 WebFilter interface의 Bean을 전부 등록시키면서 말씀주신 자동 등록이 일어나고,

SecurityContextServerWebExchange에는 설정에서 넣어주는 것 때문에 등록이 되어서 필터가 두 번 등록되는 이슈가 있었습니다.

@Bean 제거하고 SecurityContextServerWebExchange에만 등록되도록 수정하겠습니다.

감사합니다.
